#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <module_id> <faa_dir>" >&2
  exit 1
fi

module_id="$(printf "%s" "$1" | tr '[:upper:]' '[:lower:]')"
faa_dir=$2
output_dir="data/${module_id}_results/alignments"
mkdir -p $output_dir

rm -f $output_dir/*.faa
rm -f $output_dir/*.png

if [[ ! -d "$faa_dir" ]]; then
  echo "Directory not found: $faa_dir" >&2
  exit 1
fi

for faa_path in "$faa_dir"/*.faa; do
  [ -e "$faa_path" ] || continue

  filename=$(basename -- "$faa_path")
  stem="${filename%.*}"
  hmm="${filename%%[_-]*}"

  aln_path="${output_dir}/$stem.faa"
  png_path="${output_dir}/$stem.png"
  echo $aln_path

  # muscle generates alignment that better visualizes conserved peptides, use this over hmmalign
  scripts/align/muscle $faa_path $aln_path
  # not using the PNG files so skip generating them for now
  # scripts/align/mk-msa-vis $aln_path $png_path

done
