#!/bin/bash

# argument: faa file, output file

echo $1
python3 scripts/align/fasta-re.py $1 "*" --repl Z > $1.tmp.$$
echo $1.tmp.$$.faa
docker run --rm -v /Users/benjie/git/needle/data:/data pegi3s/muscle -in "/$1.tmp.$$" -out "/$2.tmp.$$"
echo $2.tmp.$$
python3 scripts/align/fasta-re.py $2.tmp.$$ Z --repl "*" > $2
rm $1.tmp.$$
rm $2.tmp.$$
